/**
 * This file is initially generated by running `npx ts-jest config:init`
 * See more:
 *  https://kulshekhar.github.io/ts-jest/docs/getting-started/installation/#jest-config-file
 *  https://jestjs.io/docs/getting-started#via-ts-jest
 */

/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: "ts-jest",

  // See more: https://jestjs.io/docs/configuration/#testenvironment-string
  testEnvironment: "./test/MyTestEnvironment",
};
